color0 #514441
color1 #ffb4ab
color2 #f2b9ae
color3 #dec0ba
color4 #d9c591
color5 #f2b9ae
color6 #dec0ba
color7 #eae0de
color8 #9e8d8a
color9 #ffb4ab
color10 #f2b9ae
color11 #dec0ba
color12 #d9c591
color13 #f2b9ae
color14 #dec0ba
color15 #eae0de

cursor                #eae0de
cursor_text_color     #171212
background            #171212
foreground            #eae0de
selection_foreground  #d5c2bf
selection_background  #514441
active_border_color   #f2b9ae
inactive_border_color #514441
url_color             #f2b9ae

active_tab_foreground   #4b261f
active_tab_background   #f2b9ae
inactive_tab_foreground #d5c2bf
inactive_tab_background #514441
cursor_trail_color      #d5c2bf
